### ISSUE TITLE
App crashes when erasing text after update

### ISSUE THREAD

**Issue by LilyTheVampire** [alialbaali/Noto#170]
Hi there!
First of all, I'd like to thank you so so much for creating such an amazing app. Noto has been my notes app for at least half an year already and has absolutely been my favorite notes app ever!
After this last update, however, I've noticed the app crashing a lot every time I try to write a note. After some minutes, I seemed to notice that this would mostly happen when I tried to erase any type of text at all.

**Comment by pgrilo** [comment]
I have the same behaviour since the last update (2.2.1). Crashes every time deleting text.

Thank you for this amazing app!

**Comment by Shkzeen** [comment]
I got two different crashes
```
FATAL EXCEPTION: main
Process: com.noto, PID: 29214
java.lang.IllegalArgumentException: No destination with ID 2131362132 is on the NavController's back stack. The current destination is a(com.noto:id/confirmationDialogFragment) label=ConfirmationDialogFragment
	at androidx.navigation.NavController.c(SourceFile:5)
	at com.noto.app.folder.i.c(SourceFile:1)
	at androidx.lifecycle.LiveData.b(Unknown Source:29)
	at androidx.lifecycle.LiveData.c(Unknown Source:44)
	at androidx.lifecycle.s.i(Unknown Source:14)
	at androidx.lifecycle.z$b.i(Unknown Source:11)
	at androidx.lifecycle.z.c(SourceFile:2)
	at m6.a.onClick(SourceFile:21)
	at android.view.View.performClick(View.java:7750)
	at com.google.android.material.button.MaterialButton.performClick(Unknown Source:3)
	at android.view.View.performClickInternal(View.java:7727)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29141)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```
and, ```
FATAL EXCEPTION: main
Process: com.noto, PID: 11736
java.lang.StringIndexOutOfBoundsException: begin 620, end 618, length 628
	at java.lang.String.checkBoundsBeginEnd(String.java:3942)
	at java.lang.String.substring(String.java:2467)
	at com.noto.app.note.NoteFragment$setupState$30.m(SourceFile:131)
	at com.noto.app.note.NoteFragment$setupState$30.R(SourceFile:13)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.c(Unknown Source:71)
	at kotlinx.coroutines.flow.FlowKt__DelayKt$debounceInternal$1$3$1.m(Unknown Source:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.s(Unknown Source:8)
	at a1.b.k0(SourceFile:141)
	at kotlinx.coroutines.selects.a$d.run(SourceFile:55)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [k1{Cancelling}@d65d4b5, Dispatchers.Main.immediate]
```
You're welcome!

**Comment by alialbaali** [comment]
I just pushed an update with a potential fix for this problem. It's gonna take few hours before it's released on Play Store. However, if you have downloaded your app through GitHub/F-Droid, please update the app with the new APK from [here](https://github.com/alialbaali/Noto/releases/tag/v2.2.1).

**Comment by pgrilo** [comment]
> I just pushed an update with a potential fix for this problem. It's gonna take few hours before it's released on Play Store. However, if you have downloaded your app through GitHub/F-Droid, please update the app with the new APK from [here](https://github.com/alialbaali/Noto/releases/tag/v2.2.1).

It seams to be fixed on my side. Awesome!
Thank you for your dedication, appreciated.

**Comment by thesupertechno** [comment]
I'm having this exact issue. I am running 2.2.1, and the app still crashes constantly. Not sure what it is, but every time it crashes, I'm always in the middle of editing a note.

**Comment by alialbaali** [comment]
Did you try updating the app?

**Comment by thesupertechno** [comment]
Yup, I'm on the latest version. Still getting the crashes

**Comment by alialbaali** [comment]
Which platform did you use to update? F-Droid, GitHub, Play Store?

**Comment by thesupertechno** [comment]
I used F-Droid to install and update Noto

**Comment by alialbaali** [comment]
F-Droid currently uses GitHub releases. Please install the new updated APK from GitHub release from [here](https://github.com/alialbaali/Noto/releases/tag/v2.2.1).

**Comment by uli-on** [comment]
I can't tell if my stacktrace has something new:

```
FATAL EXCEPTION: main
Process: com.noto, PID: 18076
java.lang.StringIndexOutOfBoundsException: String index out of range: -39
	at java.lang.String.substring(String.java:2064)
	at com.noto.app.note.NoteFragment$setupState$30.m(SourceFile:131)
	at com.noto.app.note.NoteFragment$setupState$30.R(SourceFile:13)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.c(Unknown Source:71)
	at kotlinx.coroutines.flow.FlowKt__DelayKt$debounceInternal$1$3$1.m(Unknown Source:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.s(Unknown Source:8)
	at a1.b.k0(SourceFile:141)
	at kotlinx.coroutines.selects.a$d.run(SourceFile:55)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [k1{Cancelling}@9aa7485, Dispatchers.Main.immediate]

```

**Comment by alialbaali** [comment]
Did you download the new APK from GitHub?

**Comment by uli-on** [comment]
Yes, 2.2.1 from GH.

**Comment by alialbaali** [comment]
Could you please try to download it again, and report back? Thanks

**Comment by uli-on** [comment]
For me this seems to be fixed. Thanks!

**Comment by alialbaali** [comment]
No problem!
